In [7]:
import pandas as pd

In [8]:
df=pd.read_csv('customer_shopping_behavior.csv')

In [9]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [11]:
df.describe()
#check summary statistics of the dataset by default of numerical columns only
df.describe(include='all')
#check summary statistics of the dataset by including all columns, both numerical and categorical

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [12]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [13]:
#finding median of clothing and footwearcategory review score and fill missing data with median value
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [14]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [15]:
#fixing column names by replacing spaces with underscores and converting to lowercase (snake_case)
df.columns=df.columns.str.replace(' ','_').str.lower()

In [16]:
df.rename(columns={ 'purchase_amount_(usd)':'purchase_amount'},inplace=True)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [17]:
#new column to group customers into age groups
labels=['young_adult','adult','middle_ages','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)
#qcut is used to create equal-sized bins based on the distribution of the 'age' column, and labels are assigned to each bin to create the new 'age_group' column.

In [18]:
df[['age','age_group']].head(10)

   age    age_group
0   55  middle_ages
1   19  young_adult
2   50  middle_ages
3   21  young_adult
4   45  middle_ages
5   46  middle_ages
6   63       senior
7   27  young_adult
8   26  young_adult
9   57  middle_ages

In [19]:
#purchasefrequency_days ,textual frequencies into no. of days after which the customer made a purchase again
frequency_mapping={'Fortnightly':14,'Weekly':7,'Monthly':30,'Quarterly':90,'Bi-Weekly':14,'Annually':365,'Every 3 Months':90}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)
df[['purchase_frequency_days','frequency_of_purchases']].head(10)
#map function is used to replace the textual frequencies in the 'purchase_frequency' column with their corresponding numerical values based on the defined mapping, and the new 'purchase_frequency_days' column is created to store these numerical values.

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [20]:
df[['discount_applied','promo_code_used']].head(10)
#do we actually need these columns?

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [21]:
(df['discount_applied']==df['promo_code_used']).all()
#checking if the 'discount_applied' and 'promo_code_used' columns have the same

True

In [22]:
#since both same so remove promo_code_used column
df.drop('promo_code_used',axis=1,inplace=True)
#inplace=True is used to modify the original DataFrame directly without creating a new one, and axis=1 specifies that we want to drop a column (as opposed to a row).

In [23]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.13.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

to connect with postgresql using credentials like username password etc , once connection is established we can send out dataframe to postgresql as a brand new table , nam ethe table as customer as of now

In [24]:
pip install python-dotenv psycopg2

Requirement already satisfied: python-dotenv in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (1.2.2)
Requirement already satisfied: psycopg2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
import psycopg2
from sqlalchemy import create_engine

In [26]:
conn=psycopg2.connect(
    host='localhost',user='postgres',password='Rajashreedas',dbname='customer_behavior',port=5432)

In [27]:
username='postgres'
password='Rajashreedas'
host='localhost'
port='5432'
database='customer_behavior'
engine=create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')
table_name='customer'
df.to_sql(table_name,engine,if_exists='replace',index=False)
print("DataFrame has been successfully written to the PostgreSQL database.")

DataFrame has been successfully written to the PostgreSQL database.